version: "3.9"

services:
  postgres:
    container_name: "snailycad-bot-postgres"
    image: postgres
    command: -p ${DB_PORT:-55545}
    env_file:
      - .env
    ports:
      - "${DB_PORT:-55545}:${DB_PORT:-55545}"
    volumes:
      - .data:/var/lib/postgresql/data

  api:
    container_name: "snaily-cad-bot"
    image: snaily-cad-bot:prod
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
