version: "3.9"

services:
  postgres:
    container_name: "snailycad-bot-postgres"
    image: postgres
    command: -p 55545
    env_file:
      - .env
    ports:
      - "55545:55545"
    networks:
      - cad_bot_network
    volumes:
      - ./.data:/var/lib/postgresql/data

  api:
    container_name: "snaily-cad-bot"

    user: node
    image: node:18
    command: "pnpm run start"
    volumes:
      - .:/srv/api
    env_file:
      - .env
    working_dir: /srv/api
    depends_on:
      - postgres
    networks:
      - cad_bot_network

networks:
  cad_bot_network:
    external: true
