name: Test TypeScript types

on: [push, pull_request]

jobs:
  tsc:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 20.x

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: yarn test-tsc